version: '3'

services:
  redis:
    image: redis

  pigeon:
    build: .
    links:
      - redis
    ports:
      - 5050:5050
  
  pigeon-mqtt:
    build: ../pigeon-mqtt
    links:
      - pigeon
    ports:
      - 5151:5151
