version: '3'

services:
  redis:
    image: redis

  pigeon:
    build: .
    links:
      - redis
    ports:
      - 9000:9000
      - 9001:9001
    depends_on:
      - pigeon-mqtt

  pigeon-mqtt:
    build: ../pigeon-mqtt
    ports:
      - 9010:9010
