version: '3'

services:
  redis:
    image: redis

  pigeon:
    build: .
    links:
      - redis
    ports:
      - 5050:5050
    depends_on:
      - pigeon-mqtt

  pigeon-mqtt:
    build: ../pigeon-mqtt
    ports:
      - 5151:5151
