version: '3'

services:
  redis:
    image: redis

  arango:
    image: arangodb:3.3.16
    ports:
      - 8529:8529
    environment:
      ARANGO_NO_AUTH: 1

  pigeon:
    build: .
    links:
      - arango
      - redis
    ports:
      - 80:9000
      - 9001:9001
    depends_on:
      - arango
      - pigeon-mqtt

  pigeon-mqtt:
    build: ../pigeon-mqtt
    ports:
      - 9010:9010

  pigeon-http:
    build: ../pigeon-http
    ports:
      - 9020:9020
